# -*- coding: utf-8 -*-
"""Beta distribution

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OuJUG4mqaX2AoeuHn9CNr-4hLa5xM0JU
"""

import numpy as np

from scipy.stats import beta, t, norm

from scipy.special import btdtri

import matplotlib.pyplot as plt

p = 0.8

np.random.seed(5)

num_heads = np.random.binomial(p=p, n=n)

num_tails = n - num_heads

print(num_heads,num_tails)

prior_a, prior_b = 1,1 ## initially assumed priors for heads and tails before the experiment

a = prior_a + num_heads #updating posterior

b = prior_b + num_tails #updating posterior

rv = beta(a, b)

x = np.linspace(0, 1, 100)

plt.plot(x, rv.pdf(x))

plt.show()